// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReceiptReader.Infrastructure.Data;

#nullable disable

namespace ReceiptReader.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ReceiptDbContext))]
    [Migration("20251123150725_UpdateReceiptSchemaV3")]
    partial class UpdateReceiptSchemaV3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ReceiptReader.Domain.ReceiptInfo", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("rawText");

                    b.HasKey("FileId");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("ReceiptReader.Domain.ReceiptInfo", b =>
                {
                    b.OwnsOne("ReceiptReader.Domain.ParsedField<System.DateTime?>", "TransactionDate", b1 =>
                        {
                            b1.Property<Guid>("ReceiptInfoFileId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Confidence")
                                .HasColumnType("REAL")
                                .HasColumnName("TransactionDateConfidence");

                            b1.Property<string>("SourceText")
                                .HasColumnType("TEXT")
                                .HasColumnName("TransactionDateSourceText");

                            b1.Property<DateTime?>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("TransactionDateValue");

                            b1.HasKey("ReceiptInfoFileId");

                            b1.ToTable("Receipts");

                            b1.WithOwner()
                                .HasForeignKey("ReceiptInfoFileId");
                        });

                    b.OwnsOne("ReceiptReader.Domain.ParsedField<string>", "Currency", b1 =>
                        {
                            b1.Property<Guid>("ReceiptInfoFileId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Confidence")
                                .HasColumnType("REAL")
                                .HasColumnName("CurrencyConfidence");

                            b1.Property<string>("SourceText")
                                .HasColumnType("TEXT")
                                .HasColumnName("CurrencySourceText");

                            b1.Property<string>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("CurrencyValue");

                            b1.HasKey("ReceiptInfoFileId");

                            b1.ToTable("Receipts");

                            b1.WithOwner()
                                .HasForeignKey("ReceiptInfoFileId");
                        });

                    b.OwnsOne("ReceiptReader.Domain.ParsedField<decimal?>", "TaxAmount", b1 =>
                        {
                            b1.Property<Guid>("ReceiptInfoFileId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Confidence")
                                .HasColumnType("REAL")
                                .HasColumnName("TaxAmountConfidence");

                            b1.Property<string>("SourceText")
                                .HasColumnType("TEXT")
                                .HasColumnName("TaxAmountSourceText");

                            b1.Property<decimal?>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("TaxAmountValue");

                            b1.HasKey("ReceiptInfoFileId");

                            b1.ToTable("Receipts");

                            b1.WithOwner()
                                .HasForeignKey("ReceiptInfoFileId");
                        });

                    b.OwnsOne("ParsedField", "TotalAmount", b1 =>
                        {
                            b1.Property<Guid>("ReceiptInfoFileId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Confidence")
                                .HasColumnType("REAL")
                                .HasColumnName("TotalAmountConfidence");

                            b1.Property<string>("SourceText")
                                .HasColumnType("TEXT")
                                .HasColumnName("TotalAmountSourceText");

                            b1.Property<decimal?>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("TotalAmountValue");

                            b1.HasKey("ReceiptInfoFileId");

                            b1.ToTable("Receipts");

                            b1.WithOwner()
                                .HasForeignKey("ReceiptInfoFileId");
                        });

                    b.OwnsOne("ParsedField", "VendorName", b1 =>
                        {
                            b1.Property<Guid>("ReceiptInfoFileId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Confidence")
                                .HasColumnType("REAL")
                                .HasColumnName("VendorNameConfidence");

                            b1.Property<string>("SourceText")
                                .HasColumnType("TEXT")
                                .HasColumnName("VendorNameSourceText");

                            b1.Property<string>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("VendorNameValue");

                            b1.HasKey("ReceiptInfoFileId");

                            b1.ToTable("Receipts");

                            b1.WithOwner()
                                .HasForeignKey("ReceiptInfoFileId");
                        });

                    b.Navigation("Currency")
                        .IsRequired();

                    b.Navigation("TaxAmount")
                        .IsRequired();

                    b.Navigation("TotalAmount")
                        .IsRequired();

                    b.Navigation("TransactionDate")
                        .IsRequired();

                    b.Navigation("VendorName")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
