// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReceiptReader.Infrastructure.Data;

#nullable disable

namespace ReceiptReader.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ReceiptDbContext))]
    partial class ReceiptDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ReceiptReader.Domain.AnalysisLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AnalysisDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("AnalysisDate");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("FileHash");

                    b.Property<Guid?>("ReceiptInfoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptInfoId");

                    b.ToTable("AnalysisLogs");
                });

            modelBuilder.Entity("ReceiptReader.Domain.ReceiptInfo", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("Currency");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("TaxAmount");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("TotalAmount");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("TransactionDate");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("VendorName");

                    b.HasKey("FileId");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("ReceiptReader.Domain.ReceiptLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReceiptInfoId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalLineAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptInfoId");

                    b.ToTable("ReceiptLineItem");
                });

            modelBuilder.Entity("ReceiptReader.Domain.ReceiptTaxLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReceiptInfoId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxableAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptInfoId");

                    b.ToTable("ReceiptTaxLines");
                });

            modelBuilder.Entity("ReceiptReader.Domain.AnalysisLog", b =>
                {
                    b.HasOne("ReceiptReader.Domain.ReceiptInfo", "ReceiptInfo")
                        .WithMany()
                        .HasForeignKey("ReceiptInfoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ReceiptInfo");
                });

            modelBuilder.Entity("ReceiptReader.Domain.ReceiptLineItem", b =>
                {
                    b.HasOne("ReceiptReader.Domain.ReceiptInfo", "ReceiptInfo")
                        .WithMany("LineItems")
                        .HasForeignKey("ReceiptInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReceiptInfo");
                });

            modelBuilder.Entity("ReceiptReader.Domain.ReceiptTaxLine", b =>
                {
                    b.HasOne("ReceiptReader.Domain.ReceiptInfo", "ReceiptInfo")
                        .WithMany("TaxLines")
                        .HasForeignKey("ReceiptInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReceiptInfo");
                });

            modelBuilder.Entity("ReceiptReader.Domain.ReceiptInfo", b =>
                {
                    b.Navigation("LineItems");

                    b.Navigation("TaxLines");
                });
#pragma warning restore 612, 618
        }
    }
}
