// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReceiptReader.Infrastructure.Data;

#nullable disable

namespace ReceiptReader.Migrations
{
    [DbContext(typeof(ReceiptDbContext))]
    [Migration("20251115182605_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ReceiptReader.Domain.ReceiptInfo", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FileId");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("ReceiptReader.Domain.ReceiptInfo", b =>
                {
                    b.OwnsOne("ReceiptReader.Domain.ParsedField<System.DateTime?>", "Date", b1 =>
                        {
                            b1.Property<Guid>("ReceiptInfoFileId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Confidence")
                                .HasColumnType("REAL")
                                .HasColumnName("DateConfidence");

                            b1.Property<string>("SourceText")
                                .HasColumnType("TEXT")
                                .HasColumnName("DateSourceText");

                            b1.Property<DateTime?>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("DateValue");

                            b1.HasKey("ReceiptInfoFileId");

                            b1.ToTable("Receipts");

                            b1.WithOwner()
                                .HasForeignKey("ReceiptInfoFileId");
                        });

                    b.OwnsOne("ReceiptReader.Domain.ParsedField<decimal?>", "Amount", b1 =>
                        {
                            b1.Property<Guid>("ReceiptInfoFileId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Confidence")
                                .HasColumnType("REAL")
                                .HasColumnName("AmountConfidence");

                            b1.Property<string>("SourceText")
                                .HasColumnType("TEXT")
                                .HasColumnName("AmountSourceText");

                            b1.Property<decimal?>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("AmountValue");

                            b1.HasKey("ReceiptInfoFileId");

                            b1.ToTable("Receipts");

                            b1.WithOwner()
                                .HasForeignKey("ReceiptInfoFileId");
                        });

                    b.OwnsOne("ReceiptReader.Domain.ParsedField<string>", "Store", b1 =>
                        {
                            b1.Property<Guid>("ReceiptInfoFileId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Confidence")
                                .HasColumnType("REAL")
                                .HasColumnName("StoreConfidence");

                            b1.Property<string>("SourceText")
                                .HasColumnType("TEXT")
                                .HasColumnName("StoreSourceText");

                            b1.Property<string>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("StoreValue");

                            b1.HasKey("ReceiptInfoFileId");

                            b1.ToTable("Receipts");

                            b1.WithOwner()
                                .HasForeignKey("ReceiptInfoFileId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Date")
                        .IsRequired();

                    b.Navigation("Store")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
